# numpy.array的基本操作

In [1]:
import numpy as np

In [5]:
np.random.seed(0)
x = np.arange(10)
X = np.arange(12).reshape((3,4))

In [7]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## numpy.array的基本属性

In [11]:
#维度
x.ndim

1

In [10]:
X.ndim

2

***

In [12]:
x.shape

(10,)

In [13]:
X.shape

(3, 4)

***

In [14]:
x.size

10

In [15]:
X.size

12

## numpy.array的数据访问

In [16]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[0]

0

In [18]:
x[-1]

9

In [19]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
X[1][3]#不建议

7

In [23]:
X[1,3]

7

***

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
x[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
x[2:5]

array([2, 3, 4])

In [28]:
x[::2]

array([0, 2, 4, 6, 8])

In [29]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
X[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [32]:
X[:2][:3]#结果不一样

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## Subarray of numpy.array

#### clone

In [34]:
a = X[:2,:3]
a

array([[0, 1, 2],
       [4, 5, 6]])

In [36]:
a[0,0]  = 1111
a

array([[1111,    1,    2],
       [   4,    5,    6]])

In [37]:
X

array([[1111,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [38]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a

array([[0, 1, 2],
       [4, 5, 6]])

In [40]:
b = X[:2,:3].copy()
b

array([[0, 1, 2],
       [4, 5, 6]])

In [42]:
b[0,0] = 12345
b

array([[12345,     1,     2],
       [    4,     5,     6]])

In [43]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a

array([[0, 1, 2],
       [4, 5, 6]])

In [45]:
X[0,0] = 1
X

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
b

array([[12345,     1,     2],
       [    4,     5,     6]])

## Reshape

In [47]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x.ndim

1

In [50]:
x.shape

(10,)

In [57]:
x_1 = x.reshape(2,5)
x_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x_1.shape

(2, 5)

In [60]:
x_1.ndim

2

In [62]:
x_2 = x.reshape(1,10)
print(x_2,x_2.shape,x_2.ndim)

[[0 1 2 3 4 5 6 7 8 9]] (1, 10) 2


In [63]:
X

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
X.size

12

In [65]:
A = X.reshape(-1,6)
A

array([[ 1,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [67]:
A = X.reshape(6,-1)
A

array([[ 1,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])