# numpy.array

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.4'

### Python List

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5:]

[5, 6, 7, 8, 9]

In [5]:
L[7] = 'hellow numpy'

In [6]:
L

[0, 1, 2, 3, 4, 5, 6, 'hellow numpy', 8, 9]

python list没有明确限定存储同样的类型，带来效率问题

In [7]:
import array

In [8]:
arr = array.array('i',[i for i in range(12)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [10]:
arr[7]

7

In [11]:
arr[5]='hi,array'

TypeError: an integer is required (got type str)

In [13]:
arr[5]=5.0

TypeError: integer argument expected, got float

In [15]:
arr[5]=555
arr

array('i', [0, 1, 2, 3, 4, 555, 6, 7, 8, 9, 10, 11])

array 的缺点是没有将数据做向量或矩阵，不支持基本运算

### numpy.array

In [16]:
a = np.array([i for i in range(12)])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
a[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [19]:
a[5]=5.0
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
a[7]='hellow'
a

ValueError: invalid literal for int() with base 10: 'hellow'

In [23]:
a.dtype

dtype('int64')

In [24]:
b = np.array([1,23,4.0])
b.dtype

dtype('float64')

In [28]:
c = np.array([1,2,3,4],dtype=np.float32)
c.dtype

dtype('float32')