# numpy.array合并分割

In [1]:
import numpy as np

## numpy.array 的合并

### 仅记录了一些常用的

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [10]:
np.concatenate([x,y],axis=0)

array([1, 2, 3, 4, 5, 6])

In [7]:
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.hstack([x,y])

array([1, 2, 3, 4, 5, 6])

## numpy.array 的分割

In [11]:
a =  np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
a1 , a2 ,a3 = np.split(a,[2,7])

In [13]:
a1

array([0, 1])

In [14]:
a2

array([2, 3, 4, 5, 6])

In [15]:
a3

array([ 7,  8,  9, 10, 11])

In [16]:
a1 , a2 = np.split(a,[7])
print(a1,a2)

[0 1 2 3 4 5 6] [ 7  8  9 10 11]


***

In [17]:
A = np.arange(12).reshape((3,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
A1 , A2 =  np.split(A,[1])
print(A1)
print('')
print(A2)

[[0 1 2 3]]

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
A3 , A4 = np.split(A,[2],axis=1)

In [24]:
A3

array([[0, 1],
       [4, 5],
       [8, 9]])

In [25]:
A4

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [32]:
A1 , A2 =  np.vsplit(A,[2])

In [33]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
A2

array([[ 8,  9, 10, 11]])

In [39]:
data = np.arange(12).reshape(3,4)

In [40]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
data2 , data3  = np.hsplit(data,[-1])

In [42]:
data2

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [43]:
data3

array([[ 3],
       [ 7],
       [11]])

In [44]:
data3[:,0]

array([ 3,  7, 11])